### PR TITLE
+ parsing date in sb news

### PR DESCRIPTION
**Pull request by ChiefChippy2**
**Please describe changes**

todo maybe to fetch the contents of the news? It might be useful

*Description*

- [x] I've added new features. (methods or parameters)
- [ ] I've added jsdoc and typings.
- [ ] I've fixed bug. (*optional* you can mention a issue if there is one)
- [ ] I've corrected the spelling in README, documentation, etc.
- [x] I've tested my code. (`npm run test`)

### CODE REVIEW

**Comment by StavZ** [comment]
image
7th June - 2020-06-06
1st June - 2020-05-31
👀

**Comment by ChiefChippy2** [comment]
> image
> 7th June - 2020-06-06
> 1st June - 2020-05-31
> 👀

timezone ???

**Comment by StavZ** [comment]
ah yeah

**Comment by linearaccelerator** [comment]
image
fail

**Comment by ChiefChippy2** [comment]
> image
> fail

"No api key"

**Comment by StavZ** [comment]
idk why

**Pull request merged**
