### PR TITLE
Removed Friends

### PR DESCRIPTION
**Pull request by Kathund**
Friends API

Removed all references to the friends api since hypixel removed it from the api

- [ ] I've added new features. (methods or parameters)
- [ ] I've added jsdoc and typings.
- [x] I've fixed bug. (*optional* you can mention a issue if there is one)
- [ ] I've corrected the spelling in README, documentation, etc.
- [X] I've tested my code. (`npm run test`)

### CODE REVIEW

**Comment by StavZ** [comment]
remove typings from typings/index.d.ts

**Comment by Kathund** [comment]
Removed more references to the friends system

**Comment by ChiefChippy2** [comment]
Looks good to me

**Comment by StavZ** [comment]
What's wrong with ready event?

**Comment by Kathund** [comment]
> What's wrong with ready event?

What?

**Comment by StavZ** [comment]
> > What's wrong with ready event?
> 
> What?

why you removed jsdoc for this event?

**Comment by Kathund** [comment]
> > > What's wrong with ready event?
> > 
> > 
> > What?
> 
> why you removed jsdoc for this event?

i removed all refrences to friends since the api has been removed. I dont understand what you jsdoc change you are talking about

**Comment by StavZ** [comment]
> i removed all refrences to friends since the api has been removed. I dont understand what you jsdoc change you are talking about

image

**Comment by Kathund** [comment]
> > i removed all refrences to friends since the api has been removed. I dont understand what you jsdoc change you are talking about
> 
> image

That was removed due to it showing an exmaple of something that wouldn't be possible anymore due the end point geteting removed and it getting removed from the package. If you want I can add it back but using a different example.

**Pull request merged**
