### PR TITLE
[WIP | DNM] feat(Pit): Update Pit structure

### PR DESCRIPTION
**Pull request by LiamTownsley**
Updating the Pit Structure to include all the API entries for it.

This is WORK IN PROGRESS and should not be merged. If you would like to contribute, you can do so on my branch:
https://github.com/LiamTownsley/hypixel-api-reborn/tree/patch-1

I will be making changes to this PR to fix documentation, add more classes, etc and keep it to the same standard as the rest of the repository.

If you would like to assist, create [commits](https://github.com/LiamTownsley/hypixel-api-reborn/tree/patch-1) here.

### CODE REVIEW

**Comment by ChiefChippy2** [comment]
for pit items and pit utils, you should use the ItemBytes class. it has what you need

**Comment by LiamTownsley** [comment]
> for pit items and pit utils, you should use the ItemBytes class. it has what you need

thanks @ChiefChippy2 , got told by Stav that SkyblockMember parsed it, so just took the code from there.
I'll be sure to switch it over though

**Comment by porterporter** [comment]
as brought up in the discord, what's still WIP with this commit?

**Comment by LiamTownsley2** [comment]
The WIP part was here
https://github.com/Hypixel-API-Reborn/hypixel-api-reborn/pull/196/files#diff-4fbdf931a0b42e935f8fbbab6869229cddbb145d3b9e642a1d83368b3f322af2R306-R324

**Comment by LiamTownsley2** [comment]
Can someone test if thats fine merge, I've not been active for a while

**Pull request closed without merging**
