### PR TITLE
[CHORE] Implement new endpoints + extend player class

### PR DESCRIPTION
**Pull request by ChiefChippy2**
**Please describe changes**

Accident happened (accidentally merged).... so here's the new PR

[BREAKING] grouping into .skyblock for sb endpoints

~~Help me add TS typings~~

*Description*

- [x] I've added new features. (methods or parameters)
- [x] I've added jsdoc and typings.
- [x] I've fixed bug. (*optional* you can mention a issue if there is one)
- [ ] I've corrected the spelling in README, documentation, etc.
- [x] I've tested my code. (`npm run test`)

### CODE REVIEW

**Comment by StavZ** [comment]
image

**Comment by StavZ** [comment]
image
wtf

**Comment by ChiefChippy2** [comment]
oh the filename is incorrectly cased lul

**Comment by StavZ** [comment]
image
why.. or I'm dumb

**Comment by ChiefChippy2** [comment]
> image why.. or I'm dumb

weird... let me check that out

**Comment by ChiefChippy2** [comment]
@StavZ should be fine now... it just looks kinda wacky

**Review by StavZ — COMMENTED** [review]
should _tierInfo start with underscore? (`AchievementTier.js`)

**Comment by ChiefChippy2** [comment]
> should _tierInfo start with underscore? (`AchievementTier.js`)

Well it's supposed to be "private" or like an undocumented thing, because I'd much rather people use getTier() instead of _tierInfo... but feel free to change it.
The other reason is _tierInfo doesn't parse anything at all ... it just sorts the tiers

**Comment by StavZ** [comment]
image
what is it?

**Comment by ChiefChippy2** [comment]
> image
> what is it?

uhh yeah idk how this looks in intellisense, but I extended VanityCompanions from VanityPets, therefore I have to remove this.pets for companions and instead add this.companions

**Comment by ChiefChippy2** [comment]
@StavZ mind doing the typings ty

**Review by ChiefChippy2 — COMMENTED** [review]
as mentioned by @muchnameless 

can someone help me check this is correct? I don't think there should be any issues but i'm a potato when it comes to sb

**Comment by Kathund** [comment]
@ChiefChippy2 what is happening with this pr?

**Comment by ChiefChippy2** [comment]
it's been a while since i worked on this library @Kathund .... give me a few days and I'll be able to update you on the situation as I'm a bit busy with other things rn.

**Comment by Kathund** [comment]
> it's been a while since i worked on this library @Kathund .... give me a few days and I'll be able to update you on the situation as I'm a bit busy with other things rn.

Keep me updated! Im also using the code from this to add woolwars

**Comment by Kathund** [comment]
Taken over by #508

**Pull request closed without merging**
