### PR TITLE
fix(Auction): make highestBid the highest price

### PR DESCRIPTION
**Pull request by LiamTownsley**
this will make highestBid the highest price, if it is BIN it will show BIN price, else it will show highest bid price

### CODE REVIEW

**Comment by ChiefChippy2** [comment]
Highest bid amount is not bin price

**Comment by LiamTownsley** [comment]
It may be highestBid but startingBid also inclides a BIN price, and for a project I was doing, saved a few lines of code doing it this way & there shouldn't be any unintended side effects.

**Comment by ChiefChippy2** [comment]
check auction id 9493aa028b2d4801b78ba002a93e9a3c
the bin price is not highest bid amount but starting bid

**Comment by LiamTownsley** [comment]
> check auction id 9493aa028b2d4801b78ba002a93e9a3c
> the bin price is not highest bid amount but starting bid

Auction ID "9493aa028b2d4801b78ba002a93e9a3c" is bin?

Output: https://gist.github.com/LiamTownsley/650d81cdfd4cdb557f3ad987e4c597e9

**Comment by LiamTownsley** [comment]
How this works, if the Auction is BIN, it will have both startingBid and highestBid set to the same number (as it's the highest  number).

If it's an Auction (not BIN) it will display the startingBid and the highestBid as their correct figures.

It is working as intended, @ChiefChippy2

**Comment by ChiefChippy2** [comment]
oh wait no i see what you are saying sry i wasn't entirely awake, ignore previous messages

I think its still nice to keep highest bid as is because the api does provide a value for highest bid amount and it is 0, so we shouldn't change that. you can however change the docs to say starting bid is also bin price, highest bid amount should be 0 for BIN

**Comment by LiamTownsley** [comment]
> oh wait no i see what you are saying sry i wasn't entirely awake, ignore previous messages
> 
> I think its still nice to keep highest bid as is because the api does provide a value for highest bid amount and it is 0, so we shouldn't change that. you can however change the docs to say starting bid is also bin price, highest bid amount should be 0 for BIN

Up to the repo author, I think it would be better if highestBid was the highest price - could create a seperate variable that does this instead?

**Pull request merged**
