### PR TITLE
Fix bestiary constants

### PR DESCRIPTION
**Pull request by Johannes7k75**
## Changes

I have fixed many bestiary brackets and mobs.

<details>
<summary>Screenshots</summary>

</details>

<details>
<summary>Checkboxes</summary>

- [x] I've added new features. (methods or parameters)
- [ ] I've added jsdoc and typings.
- [ ] I've fixed bug. (_optional_ you can mention a issue if there is one)
- [ ] I've corrected the spelling in README, documentation, etc.
- [ ] I've tested my code. (`npm run tests`)
- [ ] I've check for issues. (`npm run eslint`)
- [ ] I've fixed my formatting. (`npm run prettier`)

</details>

### CODE REVIEW

**Review by Kathund — APPROVED** [review]

**Comment by Kathund** [comment]
@Johannes7k75 Please see this btw https://discord.com/channels/660416184252104705/675741726077354033/1263413823000416266

**Comment by Johannes7k75** [comment]
@Kathund do you mean the TS rewrite?

**Comment by Kathund** [comment]
> @Kathund do you mean the TS rewrite?

ye dev on reborn has slowed to basically  just bug fixes while im working on reborn ts

:eyes:

**Comment by Johannes7k75** [comment]
ohh nice

**Pull request merged**
