### PR TITLE
BedWars Level Progress

### PR DESCRIPTION
**Pull request by Jok3rGRE**
**Please describe changes**

*Description*

- [x] I've added new features. (methods or parameters)
- [x] I've added jsdoc and typings.
- [ ] I've fixed bug. (*optional* you can mention a issue if there is one)
- [ ] I've corrected the spelling in README, documentation, etc.
- [x] I've tested my code. (`npm run test`)

### CODE REVIEW

**Comment by ChiefChippy2** [comment]
pretty sure bedwars' leveling system is not what you implemented there

**Comment by Jok3rGRE** [comment]
> pretty sure bedwars' leveling system is not what you implemented there

what do you mean. You can test the code.

**Comment by ChiefChippy2** [comment]
image
See, my progress should be ~44% but your thing says 92.07%.
fyi i only need 5k xp to get to lvl 84

**Comment by StavZ** [comment]
@Jok3rGRE https://github.com/Plancke/hypixel-php/blob/master/src/util/games/bedwars/ExpCalculator.php

**Pull request closed without merging**
